// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bus.proto

package bus

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cmd int32

const (
	Cmd_NONE      Cmd = 0
	Cmd_REG_SVR   Cmd = 1
	Cmd_PING      Cmd = 2
	Cmd_NEW_SVR   Cmd = 3
	Cmd_ROUTE_MSG Cmd = 4
)

var Cmd_name = map[int32]string{
	0: "NONE",
	1: "REG_SVR",
	2: "PING",
	3: "NEW_SVR",
	4: "ROUTE_MSG",
}

var Cmd_value = map[string]int32{
	"NONE":      0,
	"REG_SVR":   1,
	"PING":      2,
	"NEW_SVR":   3,
	"ROUTE_MSG": 4,
}

func (x Cmd) String() string {
	return proto.EnumName(Cmd_name, int32(x))
}

func (Cmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9aee8707d5a25b8, []int{0}
}

type ErrorCode int32

const (
	ErrorCode_SUCCESS       ErrorCode = 0
	ErrorCode_SYSTEM_UNKNOW ErrorCode = 999
)

var ErrorCode_name = map[int32]string{
	0:   "SUCCESS",
	999: "SYSTEM_UNKNOW",
}

var ErrorCode_value = map[string]int32{
	"SUCCESS":       0,
	"SYSTEM_UNKNOW": 999,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}

func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9aee8707d5a25b8, []int{1}
}

type Ping struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ping) Reset()         { *m = Ping{} }
func (m *Ping) String() string { return proto.CompactTextString(m) }
func (*Ping) ProtoMessage()    {}
func (*Ping) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9aee8707d5a25b8, []int{0}
}

func (m *Ping) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ping.Unmarshal(m, b)
}
func (m *Ping) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ping.Marshal(b, m, deterministic)
}
func (m *Ping) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ping.Merge(m, src)
}
func (m *Ping) XXX_Size() int {
	return xxx_messageInfo_Ping.Size(m)
}
func (m *Ping) XXX_DiscardUnknown() {
	xxx_messageInfo_Ping.DiscardUnknown(m)
}

var xxx_messageInfo_Ping proto.InternalMessageInfo

type RegSvrInfo struct {
	SrcId                int64    `protobuf:"varint,1,opt,name=srcId,proto3" json:"srcId,omitempty"`
	DestId               int64    `protobuf:"varint,2,opt,name=destId,proto3" json:"destId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegSvrInfo) Reset()         { *m = RegSvrInfo{} }
func (m *RegSvrInfo) String() string { return proto.CompactTextString(m) }
func (*RegSvrInfo) ProtoMessage()    {}
func (*RegSvrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9aee8707d5a25b8, []int{1}
}

func (m *RegSvrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegSvrInfo.Unmarshal(m, b)
}
func (m *RegSvrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegSvrInfo.Marshal(b, m, deterministic)
}
func (m *RegSvrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegSvrInfo.Merge(m, src)
}
func (m *RegSvrInfo) XXX_Size() int {
	return xxx_messageInfo_RegSvrInfo.Size(m)
}
func (m *RegSvrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RegSvrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RegSvrInfo proto.InternalMessageInfo

func (m *RegSvrInfo) GetSrcId() int64 {
	if m != nil {
		return m.SrcId
	}
	return 0
}

func (m *RegSvrInfo) GetDestId() int64 {
	if m != nil {
		return m.DestId
	}
	return 0
}

type NewSvrInfo struct {
	DestId               int64    `protobuf:"varint,1,opt,name=destId,proto3" json:"destId,omitempty"`
	Ip                   string   `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 string   `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewSvrInfo) Reset()         { *m = NewSvrInfo{} }
func (m *NewSvrInfo) String() string { return proto.CompactTextString(m) }
func (*NewSvrInfo) ProtoMessage()    {}
func (*NewSvrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9aee8707d5a25b8, []int{2}
}

func (m *NewSvrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewSvrInfo.Unmarshal(m, b)
}
func (m *NewSvrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewSvrInfo.Marshal(b, m, deterministic)
}
func (m *NewSvrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewSvrInfo.Merge(m, src)
}
func (m *NewSvrInfo) XXX_Size() int {
	return xxx_messageInfo_NewSvrInfo.Size(m)
}
func (m *NewSvrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NewSvrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NewSvrInfo proto.InternalMessageInfo

func (m *NewSvrInfo) GetDestId() int64 {
	if m != nil {
		return m.DestId
	}
	return 0
}

func (m *NewSvrInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NewSvrInfo) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

type RouteInfo struct {
	DestId               int64    `protobuf:"varint,1,opt,name=destId,proto3" json:"destId,omitempty"`
	DestSvr              int64    `protobuf:"varint,2,opt,name=destSvr,proto3" json:"destSvr,omitempty"`
	SrcSvr               int64    `protobuf:"varint,3,opt,name=srcSvr,proto3" json:"srcSvr,omitempty"`
	Msg                  []byte   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RouteInfo) Reset()         { *m = RouteInfo{} }
func (m *RouteInfo) String() string { return proto.CompactTextString(m) }
func (*RouteInfo) ProtoMessage()    {}
func (*RouteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9aee8707d5a25b8, []int{3}
}

func (m *RouteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteInfo.Unmarshal(m, b)
}
func (m *RouteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteInfo.Marshal(b, m, deterministic)
}
func (m *RouteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteInfo.Merge(m, src)
}
func (m *RouteInfo) XXX_Size() int {
	return xxx_messageInfo_RouteInfo.Size(m)
}
func (m *RouteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RouteInfo proto.InternalMessageInfo

func (m *RouteInfo) GetDestId() int64 {
	if m != nil {
		return m.DestId
	}
	return 0
}

func (m *RouteInfo) GetDestSvr() int64 {
	if m != nil {
		return m.DestSvr
	}
	return 0
}

func (m *RouteInfo) GetSrcSvr() int64 {
	if m != nil {
		return m.SrcSvr
	}
	return 0
}

func (m *RouteInfo) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type CommonMessage struct {
	Code                 Cmd         `protobuf:"varint,1,opt,name=code,proto3,enum=bus.Cmd" json:"code,omitempty"`
	ErrorCode            ErrorCode   `protobuf:"varint,2,opt,name=errorCode,proto3,enum=bus.ErrorCode" json:"errorCode,omitempty"`
	SeqId                int32       `protobuf:"varint,3,opt,name=seqId,proto3" json:"seqId,omitempty"`
	Ping                 *Ping       `protobuf:"bytes,10,opt,name=ping,proto3" json:"ping,omitempty"`
	SvrInfo              *RegSvrInfo `protobuf:"bytes,11,opt,name=svrInfo,proto3" json:"svrInfo,omitempty"`
	NewSvrInfo           *NewSvrInfo `protobuf:"bytes,12,opt,name=newSvrInfo,proto3" json:"newSvrInfo,omitempty"`
	RouteInfo            *RouteInfo  `protobuf:"bytes,13,opt,name=routeInfo,proto3" json:"routeInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CommonMessage) Reset()         { *m = CommonMessage{} }
func (m *CommonMessage) String() string { return proto.CompactTextString(m) }
func (*CommonMessage) ProtoMessage()    {}
func (*CommonMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9aee8707d5a25b8, []int{4}
}

func (m *CommonMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonMessage.Unmarshal(m, b)
}
func (m *CommonMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonMessage.Marshal(b, m, deterministic)
}
func (m *CommonMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonMessage.Merge(m, src)
}
func (m *CommonMessage) XXX_Size() int {
	return xxx_messageInfo_CommonMessage.Size(m)
}
func (m *CommonMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CommonMessage proto.InternalMessageInfo

func (m *CommonMessage) GetCode() Cmd {
	if m != nil {
		return m.Code
	}
	return Cmd_NONE
}

func (m *CommonMessage) GetErrorCode() ErrorCode {
	if m != nil {
		return m.ErrorCode
	}
	return ErrorCode_SUCCESS
}

func (m *CommonMessage) GetSeqId() int32 {
	if m != nil {
		return m.SeqId
	}
	return 0
}

func (m *CommonMessage) GetPing() *Ping {
	if m != nil {
		return m.Ping
	}
	return nil
}

func (m *CommonMessage) GetSvrInfo() *RegSvrInfo {
	if m != nil {
		return m.SvrInfo
	}
	return nil
}

func (m *CommonMessage) GetNewSvrInfo() *NewSvrInfo {
	if m != nil {
		return m.NewSvrInfo
	}
	return nil
}

func (m *CommonMessage) GetRouteInfo() *RouteInfo {
	if m != nil {
		return m.RouteInfo
	}
	return nil
}

var BUS_structType = map[string]interface{}{
	"Ping":          Ping{},
	"RegSvrInfo":    RegSvrInfo{},
	"NewSvrInfo":    NewSvrInfo{},
	"RouteInfo":     RouteInfo{},
	"CommonMessage": CommonMessage{},
}

func init() {
	proto.RegisterEnum("bus.Cmd", Cmd_name, Cmd_value)
	proto.RegisterEnum("bus.ErrorCode", ErrorCode_name, ErrorCode_value)
	proto.RegisterType((*Ping)(nil), "bus.Ping")
	proto.RegisterType((*RegSvrInfo)(nil), "bus.RegSvrInfo")
	proto.RegisterType((*NewSvrInfo)(nil), "bus.NewSvrInfo")
	proto.RegisterType((*RouteInfo)(nil), "bus.RouteInfo")
	proto.RegisterType((*CommonMessage)(nil), "bus.CommonMessage")
}

func init() { proto.RegisterFile("bus.proto", fileDescriptor_e9aee8707d5a25b8) }

var fileDescriptor_e9aee8707d5a25b8 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xeb, 0x3f, 0x4d, 0xea, 0x49, 0x1d, 0xac, 0x11, 0x42, 0x7b, 0x00, 0x29, 0xf2, 0x29,
	0x54, 0x55, 0x91, 0xca, 0x8d, 0x23, 0x96, 0x15, 0x2c, 0x14, 0xa7, 0xda, 0x6d, 0xa8, 0x38, 0x45,
	0x24, 0x5e, 0x2c, 0x1f, 0xec, 0x35, 0xbb, 0x4e, 0xf9, 0x2e, 0x7c, 0x41, 0xbe, 0x06, 0xda, 0x71,
	0x1d, 0xe7, 0xc4, 0x6d, 0xde, 0xdb, 0xdf, 0xb3, 0x47, 0x6f, 0x17, 0x82, 0xfd, 0xd1, 0xdc, 0xb5,
	0x5a, 0x75, 0x0a, 0xbd, 0xfd, 0xd1, 0xc4, 0x13, 0xf0, 0x1f, 0xaa, 0xa6, 0x8c, 0x3f, 0x01, 0x70,
	0x59, 0x8a, 0x67, 0x9d, 0x35, 0x3f, 0x15, 0xbe, 0x86, 0x4b, 0xa3, 0x0f, 0x59, 0xc1, 0x9c, 0x85,
	0xb3, 0xf4, 0x78, 0x2f, 0xf0, 0x0d, 0x4c, 0x0a, 0x69, 0xba, 0xac, 0x60, 0x2e, 0xd9, 0x2f, 0x2a,
	0xfe, 0x02, 0x90, 0xcb, 0xdf, 0x43, 0x76, 0xa4, 0x9c, 0x73, 0x0a, 0xe7, 0xe0, 0x56, 0x2d, 0x25,
	0x03, 0xee, 0x56, 0x2d, 0x22, 0xf8, 0xad, 0xd2, 0x1d, 0xf3, 0xc8, 0xa1, 0x39, 0x2e, 0x21, 0xe0,
	0xea, 0xd8, 0xc9, 0xff, 0x7e, 0x88, 0xc1, 0xd4, 0x4e, 0xe2, 0x59, 0xbf, 0xec, 0x31, 0x48, 0x9b,
	0x30, 0xfa, 0x60, 0x0f, 0xbc, 0x3e, 0xd1, 0x2b, 0x8c, 0xc0, 0xab, 0x4d, 0xc9, 0xfc, 0x85, 0xb3,
	0xbc, 0xe6, 0x76, 0x8c, 0xff, 0xb8, 0x10, 0x26, 0xaa, 0xae, 0x55, 0xb3, 0x96, 0xc6, 0xfc, 0x28,
	0x25, 0xbe, 0x05, 0xff, 0xa0, 0x0a, 0x49, 0xff, 0x9a, 0xdf, 0x5f, 0xdd, 0xd9, 0x9e, 0x92, 0xba,
	0xe0, 0xe4, 0xe2, 0x2d, 0x04, 0x52, 0x6b, 0xa5, 0x13, 0x8b, 0xb8, 0x84, 0xcc, 0x09, 0x49, 0x07,
	0x97, 0x8f, 0x00, 0xd5, 0x27, 0x7f, 0x65, 0x05, 0xad, 0x71, 0xc9, 0x7b, 0x81, 0xef, 0xc0, 0x6f,
	0xab, 0xa6, 0x64, 0xb0, 0x70, 0x96, 0xb3, 0xfb, 0x80, 0xe2, 0xb6, 0x7b, 0x4e, 0x36, 0xbe, 0x87,
	0xa9, 0xe9, 0x2b, 0x64, 0x33, 0x22, 0x5e, 0x11, 0x31, 0xde, 0x0a, 0x1f, 0xce, 0xf1, 0x03, 0x40,
	0x73, 0x2a, 0x9c, 0x5d, 0x9f, 0xd1, 0xe3, 0x3d, 0xf0, 0x33, 0xc4, 0xae, 0xaf, 0x87, 0x5e, 0x59,
	0x48, 0x7c, 0xbf, 0xfe, 0xa9, 0x6d, 0x3e, 0x02, 0x37, 0x9f, 0xc1, 0x4b, 0xea, 0x02, 0xaf, 0xc0,
	0xcf, 0x37, 0x79, 0x1a, 0x5d, 0xe0, 0x0c, 0xa6, 0x3c, 0x5d, 0xed, 0xc4, 0x37, 0x1e, 0x39, 0xd6,
	0x7e, 0xc8, 0xf2, 0x55, 0xe4, 0x5a, 0x3b, 0x4f, 0x9f, 0xc8, 0xf6, 0x30, 0x84, 0x80, 0x6f, 0xb6,
	0x8f, 0xe9, 0x6e, 0x2d, 0x56, 0x91, 0x7f, 0x73, 0x0b, 0xc1, 0xa9, 0x1a, 0x0b, 0x8a, 0x6d, 0x92,
	0xa4, 0x42, 0x44, 0x17, 0x88, 0x10, 0x8a, 0xef, 0xe2, 0x31, 0x5d, 0xef, 0xb6, 0xf9, 0xd7, 0x7c,
	0xf3, 0x14, 0xfd, 0x9d, 0xee, 0x27, 0xf4, 0x22, 0x3f, 0xfe, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x24,
	0x85, 0xfc, 0x1d, 0x9e, 0x02, 0x00, 0x00,
}
